from dataclasses import dataclass, field
from typing import List, Dict, Optional
import json

@dataclass
class SemanticNode:
    """
    Represents a discrete semantic node in the Directed Acyclic Discourse Graph.
    """
    node_id: str
    concept: str
    # Vector quantized index from the Graph VQ-Transformer
    vq_index: int 
    attributes: Dict[str, str] = field(default_factory=dict)

@dataclass
class SemanticEdge:
    """
    Represents a directed relation between two semantic nodes.
    """
    source_id: str
    target_id: str
    relation_type: str
    weight: float = 1.0

@dataclass
class DiscourseGraph:
    """
    The canonical macroplan generated by Module 1 and passed to Module 3 (Realizer).
    """
    graph_id: str
    nodes: List[SemanticNode]
    edges: List[SemanticEdge]
    metadata: Dict[str, str] = field(default_factory=dict)

    def to_json(self) -> str:
        """Serializes the graph for inter-module transfer."""
        return json.dumps({
            "graph_id": self.graph_id,
            "nodes": [n.__dict__ for n in self.nodes],
            "edges": [e.__dict__ for e in self.edges],
            "metadata": self.metadata
        }, indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> 'DiscourseGraph':
        """Deserializes the graph from inter-module transfer."""
        data = json.loads(json_str)
        nodes = [SemanticNode(**n) for n in data["nodes"]]
        edges = [SemanticEdge(**e) for e in data["edges"]]
        return cls(
            graph_id=data["graph_id"],
            nodes=nodes,
            edges=edges,
            metadata=data.get("metadata", {})
        )
